version: '3.8'

services:
  db:
    image: postgres
    env_file:
      - ./pdes-bramirez-backend/.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./pdes-bramirez-backend
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
