global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'apc-pdes-prometheus'
    static_configs:
    - targets: ['apc-pdes-prometheus:9090']
    
  - job_name: 'apc-pdes-cadvisor'
    static_configs:
    - targets: ['apc-pdes-cadvisor:8080']

  - job_name: 'apc-pdes-node-exporter'
    static_configs:
    - targets: ['apc-pdes-node-exporter:9100']    

  - job_name: 'apc-pdes-backend'
    static_configs:
    - targets: ['apc-pdes-backend:3001'] 
    #metrics_path: '/metrics'
    #metrics_path: '/prometheus'